### ISSUE TITLE
Integration with pre-commit

### ISSUE THREAD

**Issue by krish7919** [dkorunic/betteralign#22]
I am trying to integrate this with `pre-commit` but facing issues when the file names are passed to the hook.

Configuration:

```
- repo: local
    hooks:
      # Use `$ go install github.com/dkorunic/betteralign/cmd/betteralign@latest`
      # to install.
      - id: betteralign
        name: betteralign
        description: Fix struct alignment.
        entry: betteralign -test=false -generated_files=false
        language: system
```

I have edits to the CI config, `.golangci.yml` config and to Go files.

Error:
```
-: named files must all be in one directory; have test/integration/lib and internal/transport/http/lib
betteralign: analysis skipped due to errors in package
betteralign: -: named files must be .go files: .golangci.yml
-: named files must all be in one directory; have test/integration and internal/transport/http
betteralign: analysis skipped due to errors in package
betteralign: -: named files must be .go files: .pre-commit-config.yaml
...
```

Using `entry: betteralign -test=false -generated_files=false ./...` as the command results in:

```
betteralign: -: named files must be .go files: ./...
betteralign: -: named files must be .go files: ./...
betteralign: -: named files must be .go files: ./...
betteralign: -: named files must be .go files: ./...
betteralign: -: named files must be .go files: ./...
betteralign: -: named files must be .go files: ./...
betteralign: -: named files must be .go files: ./...
betteralign: -: named files must be .go files: ./...
betteralign: -: named files must be .go files: ./...
```

**Comment by dkorunic** [comment]
It is completely related to your CI hook and how `singlechecker` works. I would always recommend doing a shallow Git repo copy and running betteralign across all whole project through `./...` to get an analysis on the whole AST tree of the project. Sadly, there is nothing available to tweak and/or change in `singlechecker` since that entirely defined by Go team.

**Comment by ccoVeille** [comment]
Isn't the `pass_filenames` option you are looking for?

```yaml
- repo: local
    hooks:
      # Use `$ go install github.com/dkorunic/betteralign/cmd/betteralign@latest`
      # to install.
      - id: betteralign
        name: betteralign
        description: Fix struct alignment.
        entry: betteralign -test=false -generated_files=false
        language: system
        pass_filenames: false
```

This will launch betteralign on all files, on each commit.
